require('plugins')
require('settings')
--require('keymap')
--require('color')

---- PLUGIN CONFIG ----
require('config.alpha-nvim')
require('config.lualine')
require('config.lualine')
require('config.mason')
require('config.lspconfig')
require('config.null_ls')
-- require('config.lsp_inlayhints')
require('config.vimtex')
require('config.instant')
require('config.snippets')
require('config.luasnips')
-- require('config.mini')
require('config.supercollider')
require('config.telescope')
require('config.treesitter')
require('config.cmp-nvim-lsp')
require('config.filetype')
require('config.neotree')
require('config.which-key')
require('config.cppman')
require('config.fterm')
require('config.high-str')
require('config.rust-tools')
require('config.comment')
require('config.surround')
require('config.golang')
require('config.mind')
require('config.mdpreview')
-- require('config.hover')
-- require('config.nvim-tree')
-- require('config.microcontroller')

