# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME=""

PROMPT='%B%F{203}%n%F{202}@%F{203}%m%b%F{15}:%F{141}%(5~|%-1~/…/%3~|%4~)%f '
RPROMPT='%F{7}[ %* - %D ]'

plugins=(git aliases nmap)

source $ZSH/oh-my-zsh.sh

if [ -f ~/.bash_profile ]; then 
    . ~/.bash_profile;
fi
export PATH="/usr/local/sbin:$PATH"

# Put the line below in ~/.zshrc:
#
#   eval "$(jump shell zsh)"
#
# The following lines are autogenerated:

__jump_chpwd() {
  jump chdir
}

jump_completion() {
  reply="'$(jump hint "$@")'"
}

j() {
  local dir="$(jump cd $@)"
  test -d "$dir" && cd "$dir"
}

typeset -gaU chpwd_functions
chpwd_functions+=__jump_chpwd

compctl -U -K jump_completion j

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="/usr/local/opt/llvm/bin:$PATH"

if [ -f ~/.bash_profile ]; then 
    . ~/.bash_profile;
fi

export PATH="/usr/local/opt/texinfo/bin:$PATH"
